[package]
name = 'ol_engine'
version = '0.1.0'
edition = '2021'

[dependencies]
log = '0.4'
winit = '0.29'
ol_windowing = { path = '../windowing/'}
ol_renderer = { path = '../renderer/'}

[features]
default = []
