[package]
name = "ol_engine"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
ol_renderer = { path = "../renderer" }
ol_windowing = { path = "../windowing" }
winit = "0.30"
